docs: mention what Tidelift and tidelift-me-up do
JoshuaKGoldberg/tidelift-me-up-site pull request #789
Opened 2024-11-14 22:44 UTC by maggienegm

## PR Checklist

- [x] Addresses an existing open issue: fixes #18 
- [x] That issue was marked as [`status: accepting prs`](https://github.com/JoshuaKGoldberg/tidelift-me-up-site/issues?q=is%3Aopen+is%3Aissue+label%3A%22status%3A+accepting+prs%22)
- [x] Steps in [CONTRIBUTING.md](https://github.com/JoshuaKGoldberg/tidelift-me-up-site/blob/main/.github/CONTRIBUTING.md) were taken

## Overview

A description of Tidelift and tidelift-me-up was added to the `README.md`.

✨

2024-11-15 14:00 UTC, JoshuaKGoldberg approved these changes
💯 fantastic first repo contribution, thank you!

![Cartoon french chef with making the chef's kiss gesture. Caption: "PERFECTO!"](https://github.com/user-attachments/assets/9a5c5fcb-b6cc-445f-9e4c-0bc8c41f1150)

2024-11-15 14:02 UTC, JoshuaKGoldberg requested changes
Wait, sorry, _one_ little nitpick to request changes on 😄.

I recognize most English language style guides put punctuation inside quotes. But I disagree with that and especially in programming contexts think it's weird and inaccurate.

https://www.youtube.com/watch?v=UmZTzr0f5dw

2024-11-15 14:02 UTC, JoshuaKGoldberg commented on README.md
> +Through Tidelift, companies contribute to a fund that is distributed monthly to maintainers of eligible open-source packages in a process called "lifting."
Oh almost missed this:

```suggestion
Through Tidelift, companies contribute to a fund that is distributed monthly to maintainers of eligible open-source packages in a process called "lifting".
```

2024-11-15 19:47 UTC, maggienegm commented
No worries! I respect the council's decision 🫡 lol

2024-11-16 16:27 UTC, JoshuaKGoldberg approved these changes
🚀 thanks!

2024-11-16 16:27 UTC, merged

2024-11-16 16:28 UTC, JoshuaKGoldberg commented
@all-contributors please add @maggienegm for doc.

> 🤖 Beep boop! This comment was added automatically by [all-contributors-auto-action](https://github.com/marketplace/actions/all-contributors-auto-action).
> Not all contributions can be detected from Git & GitHub alone. Please comment any missing contribution types this bot missed.
> ...and of course, thank you for contributing! 💙