feat: add dynamic metadata for search results
JoshuaKGoldberg/tidelift-me-up-site pull request #842
Opened 2024-12-20 00:38 UTC by maggienegm

## PR Checklist

- [x] Addresses an existing open issue: fixes #67 
- [x] That issue was marked as [`status: accepting prs`](https://github.com/JoshuaKGoldberg/tidelift-me-up-site/issues?q=is%3Aopen+is%3Aissue+label%3A%22status%3A+accepting+prs%22)
- [x] Steps in [CONTRIBUTING.md](https://github.com/JoshuaKGoldberg/tidelift-me-up-site/blob/main/.github/CONTRIBUTING.md) were taken

## Overview

This PR introduces dynamic metadata generation for the home/search page. It's metadata is now dynamically generated based on the` searchParams` in the URL. When no `searchParams` are provided, the default metadata is used, maintaining the previous behavior.

I've also extracted the API-related logic into a separate file to improve code readability and maintainability.

2025-01-06 15:06 UTC, JoshuaKGoldberg commented on src/app/layout.tsx
> +		"Check if your npm packages are eligible for Tidelift funding. 💸",
[Praise] Oh, thanks, good catch!

2025-01-09 21:55 UTC, JoshuaKGoldberg commented
Just noting for future reference, some test values:

* https://tidelift-me-up-site-git-fork-mag-dcddf3-josh-goldbergs-projects.vercel.app/?username=joshuakgoldberg&since=2024-11-06: as an example of 1 found package
* https://tidelift-me-up-site-git-fork-mag-dcddf3-josh-goldbergs-projects.vercel.app/?username=joshuakgoldberg: as an example of multiple found packages

2025-01-09 22:37 UTC, JoshuaKGoldberg requested changes
🚀 This is looking great, thank you so much! Really excited to finally fix this darn accessibility/title bug.

Left a few comments and I think only about half of them are actually blockers. LMK what you think! 🙌

2025-01-09 22:37 UTC, JoshuaKGoldberg commented on src/app/page.tsx
> +	if (!username) {
[Refactor] I think it'd be nice to do this _"if no username, return default metadata"_ check earlier on. We can avoid the overhead of calling to an async function if we parse options first and bail out otherwise.

I know `await fetchData(...)` right now is super fast, but just conceptually an async tick is nice to avoid - and these api helpers tend to get slower over time.

How about:

1. Also making `getOptions` available to this file (either from `fetchData.ts` or some `getOptions.ts`/`options.ts` file)
2. Having the code do the `options.username` check first
3. Then only call to `fetchData` after that

2025-01-09 22:37 UTC, JoshuaKGoldberg commented on src/app/page.tsx
> +import { metadata as defaultMetadata } from "./layout";
[Non-Actionable] It would be nice if this had an image... but that's definitely out of scope for this PR 😄. Probably a lot more work. I don't even know what that image would look like.

Opinion: someone should file a feature request issue after this suggesting adding image(s) to the metadata. If you want to, awesome - but I can if you don't have time. 🙂

2025-01-09 22:37 UTC, JoshuaKGoldberg commented on src/utils/fetchData.ts
> +export type SearchParamsType = Record<string, unknown>;
[Naming] Ending with `*Type` isn't common practice anymore. I'd just call them the stuff before that:

```suggestion
export type Options = Record<string, unknown>;
export type SearchParams = Record<string, unknown>;
```

...or if you want to disambiguate, maybe `DataOptions` or `FetchOptions` or `TideliftMeUpSiteOptions` or ... something. Up to you. 😄

2025-01-09 22:37 UTC, JoshuaKGoldberg commented on src/app/page.tsx
> +	const { options, result } = await fetchData(searchParams);
[Question] Now there are two calls to the Tidelift API per page load 😬. That's probably not ideal? But I don't do enough Next.js app layout code to know the right pattern for this. Do you know if there's a good way to deduplicate? Surely something in Next.js handles this well.

2025-01-09 22:37 UTC, JoshuaKGoldberg commented on src/app/page.tsx
> +	const packageCount = Array.isArray(result) ? result.length : 0;
[Non-Actionable] Noting from QA: there's no way in the tidelift-me-up package to know that the reason for no packages is that the user didn't exist. Tracked here: https://github.com/JoshuaKGoldberg/tidelift-me-up/issues/17. So, explicitly saying I don't think we need to block the PR on giving a specific description for that. IF you really want to get that in first I'm ok waiting, but otherwise by default I'd just suggest we go with a followup issue. What do you think?

> ```plaintext
> Could not find {username} on npm.
> ```

2025-01-09 22:37 UTC, JoshuaKGoldberg commented on src/app/page.tsx
> +	const packageCount = Array.isArray(result) ? result.length : 0;
[Bug] If `fetchData` returns an `Error`, we'd want to give a specific error-y description. Like a _"could not find packages for ..."_ or something like that.

Btw, just so I don't forget them later, I think these are the five total cases that need to be handled:

* Unknown error from the try/catch in `fetchData`
* Username does not exist (blocked, see other comment on this line)
* 0 packages found
* 1 package found
* Multiple packages found

2025-01-10 22:04 UTC, maggienegm commented on src/app/page.tsx
> +import { metadata as defaultMetadata } from "./layout";
Great suggestion! I went ahead and created a [PR](https://github.com/JoshuaKGoldberg/tidelift-me-up-site/issues/843) 😄

2025-01-10 22:47 UTC, maggienegm commented on src/app/page.tsx
> +	const packageCount = Array.isArray(result) ? result.length : 0;
I agree with not blocking this PR and instead creating a follow up issue to address this bug. I went ahead and created an [issue](https://github.com/JoshuaKGoldberg/tidelift-me-up-site/issues/844) so this can be fixed when the tidelift-me-up package is updated.

2025-01-13 02:00 UTC, JoshuaKGoldberg commented on src/app/page.tsx
> +import { metadata as defaultMetadata } from "./layout";
🙌 thanks!

2025-01-13 02:00 UTC, JoshuaKGoldberg commented on src/app/page.tsx
> +	const packageCount = Array.isArray(result) ? result.length : 0;
Thanks!

2025-01-14 17:05 UTC, maggienegm commented on src/app/page.tsx
> +	const { options, result } = await fetchData(searchParams);
Took some time to dig into the docs and do some research and found that:

- `generateMetadata` and `Home` run separately in the Next.js app lifecycle. Although both are executed server-side, `generateMetadata` is run first in isolation and cannot directly pass data to `Home` after it’s done running. So either way, there would still be duplicate fetch calls.
- solution: implementing cache so that the data is consistent between both `generateMetadata` and `Home` despite the duplicate fetch calls

2025-01-14 18:13 UTC, maggienegm commented
I just wanted to note that I've added caching to ensure data consistency between the `generateMetadata` and `Home` functions. Since these functions are run separately in the Next.js app lifecycle and cannot share data directly, they will still need to call `fetchData` separately, which includes the risk of data inconsistencies. Caching is one solution to address this.

I didn't see any existing caching in the app, so I chose [node-cache](https://www.npmjs.com/package/node-cache). The `node-cache` package is a non-persistent in-memory caching solution. (Since this app doesn't have a traditional backend, it would store the data temporarily in the server's memory (RAM).) I believe this fits our use case since we don't need to have the data persist once a user closes the app. This will also ensure data consistency without having to make more fetch requests than needed.

With all that being said, would love to hear your thoughts!

2025-01-15 21:36 UTC, maggienegm commented
Replaced `node-cache` with Next.js's built-in [`cache` function](https://nextjs.org/docs/app/building-your-application/caching#react-cache-function).

2025-01-20 16:50 UTC, JoshuaKGoldberg approved these changes
This is great, thanks! The use of `cache` makes a lot of sense to me.

![Wiggling drawn animation of the 100 emoji](https://github.com/user-attachments/assets/d2f98654-c805-4485-b4e8-c6b735883e0c)

2025-01-20 16:50 UTC, JoshuaKGoldberg commented on src/app/page.tsx
> +	const { options, result } = await fetchData(searchParams);
💯

2025-01-20 16:51 UTC, JoshuaKGoldberg commented on src/app/page.tsx
> +	const { options, result } = await fetchData(searchParams);
💯 TIL, thanks for digging into that. The `cache` solution seems like the right one to me too.

2025-01-20 16:51 UTC, merged